#!/usr/bin/env python3
"""Regenerate wiki/hot.md from wiki/log.md while preserving Next Actions."""

from __future__ import annotations

from datetime import date
from pathlib import Path
import re


ROOT = Path(__file__).resolve().parent
HOT = ROOT / "hot.md"
LOG = ROOT / "log.md"
INDEX = ROOT / "index.md"

NEXT_START = "<!-- NEXT_ACTIONS_START -->"
NEXT_END = "<!-- NEXT_ACTIONS_END -->"
DEFAULT_NEXT = """## Next Actions

- Work normally; the agent maintains this wiki before finishing substantive work.
"""


def read_text(path: Path) -> str:
    try:
        return path.read_text(encoding="utf-8")
    except OSError:
        return ""


def preserve_next_actions(existing: str) -> str:
    pattern = re.compile(
        rf"{re.escape(NEXT_START)}\s*(.*?)\s*{re.escape(NEXT_END)}",
        re.DOTALL,
    )
    match = pattern.search(existing)
    if match:
        return match.group(1).strip() + "\n"
    return DEFAULT_NEXT


def parse_log_entries(text: str) -> list[str]:
    entries = []
    for line in text.splitlines():
        if line.startswith("## ["):
            entries.append(line.removeprefix("## ").strip())
    return entries


def index_page_count(text: str) -> int:
    return sum(1 for line in text.splitlines() if line.lstrip().startswith("- [["))


def content_folder_counts() -> list[tuple[str, int]]:
    folders = ["work-items", "concepts", "research", "reference", "Failed Ideas"]
    counts = []
    for folder in folders:
        path = ROOT / folder
        try:
            count = sum(1 for item in path.glob("*.md") if item.name != "README.md")
        except OSError:
            count = 0
        counts.append((folder, count))
    return counts


def build_hot() -> str:
    existing = read_text(HOT)
    next_actions = preserve_next_actions(existing)
    log_entries = parse_log_entries(read_text(LOG))
    index_count = index_page_count(read_text(INDEX))
    counts = content_folder_counts()

    recent = log_entries[-8:]
    recent_block = "\n".join(f"- {entry}" for entry in reversed(recent))
    if not recent_block:
        recent_block = "- No log entries found."

    counts_block = "\n".join(f"- `{folder}/`: {count}" for folder, count in counts)

    return f"""<!-- AUTO-GENERATED by wiki/update_hot.py. Do not hand-edit outside the Next Actions block. -->

# Current State

This page is auto-generated from wiki files. Do not hand-edit outside the marked Next Actions block.

## Summary

- Last regenerated: {date.today().isoformat()}
- Indexed wiki pages: {index_count}
- Main unit of work: work items in `wiki/work-items/`
- Content counts:
{counts_block}

## Recent Log Entries

{recent_block}

{NEXT_START}
{next_actions.rstrip()}
{NEXT_END}
"""


def main() -> int:
    try:
        HOT.write_text(build_hot(), encoding="utf-8")
    except OSError:
        return 0
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
